# Copyright (c) Microsoft Corp. All Rights Reserved.

# AMQP Stack for consumption by packages in the Azure SDK.
[package]
name = "azure_core_amqp"
version = "0.9.0"
description = "Rust client library for the AMQP protocol"
readme = "README.md"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage = "https://github.com/azure/azure-sdk-for-rust/sdk/core/azure_core_amqp"
documentation = "https://docs.rs/azure_core_amqp"

keywords = ["sdk", "azure", "rest", "iot", "cloud"]
categories = ["api-bindings"]

edition.workspace = true

[dependencies]
async-trait.workspace = true
azure_core = { path = "../azure_core", version = "0.30.0", default-features = false }
fe2o3-amqp = { workspace = true, optional = true }
fe2o3-amqp-cbs = { workspace = true, optional = true }
fe2o3-amqp-ext = { workspace = true, optional = true }
fe2o3-amqp-management = { workspace = true, optional = true }
fe2o3-amqp-types = { workspace = true, optional = true }
serde.workspace = true
serde_amqp = { workspace = true, optional = true }
serde_bytes = { workspace = true, optional = true }
tokio.workspace = true
tracing.workspace = true
typespec.workspace = true
typespec_macros.workspace = true

[dev-dependencies]
serde_json.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[features]
default = ["fe2o3_amqp", "fe2o3-amqp/native-tls"]
ffi = []
test = []
fe2o3_amqp = [
  "dep:fe2o3-amqp",
  "fe2o3-amqp-types",
  "fe2o3-amqp-ext",
  "fe2o3-amqp-management",
  "fe2o3-amqp-cbs",
  "serde_amqp",
  "serde_bytes",
]

[lints]
workspace = true

[package.metadata.docs.rs]
features = ["fe2o3_amqp"]
