[package]
name = "azure_security_keyvault_secrets"
version = "0.9.0"
description = "Rust wrappers around Microsoft Azure REST APIs - Azure Key Vault Secrets"
readme = "README.md"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage = "https://github.com/azure/azure-sdk-for-rust"
documentation = "https://docs.rs/azure_security_keyvault_secrets"
keywords = ["sdk", "azure", "keyvault", "security", "secrets"]
categories = ["api-bindings"]

[features]
default = ["azure_core/default"]

[dependencies]
async-trait = { workspace = true }
azure_core = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
typespec_client_core = { workspace = true, features = ["derive"] }

[dev-dependencies]
azure_core_test = { workspace = true, features = [
  "tracing",
] }
azure_identity.workspace = true
azure_security_keyvault_test = { path = "../azure_security_keyvault_test" }
rand.workspace = true
tokio.workspace = true

[build-dependencies]
rustc_version.workspace = true

[lints]
workspace = true

[[bench]]
name = "perf"
path = "perf/get_secret.rs"
harness = false
