[package]
name = "azure_data_cosmos"
version = "0.19.0"
description = "Rust wrappers around Microsoft Azure REST APIs - Azure Cosmos DB"
readme = "README.md"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage = "https://github.com/azure/azure-sdk-for-rust"
documentation = "https://docs.rs/azure_data_cosmos"
keywords = ["sdk", "azure", "rest", "cloud", "cosmos", "database"]
categories = ["api-bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
azure_core.workspace = true
typespec_client_core = { workspace = true, features = ["derive"] }
tracing.workspace = true
url.workspace = true
serde.workspace = true

[dev-dependencies]
tokio.workspace = true
serde_json.workspace = true
azure_identity.workspace = true
clap.workspace = true
time.workspace = true
azure_testing.workspace = true

[lints]
workspace = true

[features]
default = ["hmac_rust"]
hmac_rust = ["azure_core/hmac_rust"]
hmac_openssl = ["azure_core/hmac_openssl"]
key_auth = [] # Enables support for key-based authentication (Primary Keys and Resource Tokens)

[package.metadata.docs.rs]
features = ["key_auth"]
