[package]
name = "azure_data_cosmos"
version = "0.31.0"
description = "Rust wrappers around Microsoft Azure REST APIs - Azure Cosmos DB"
readme = "README.md"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage = "https://github.com/azure/azure-sdk-for-rust"
documentation = "https://docs.rs/azure_data_cosmos"
keywords = ["sdk", "azure", "rest", "cloud", "cosmos"]
categories = ["api-bindings"]

[dependencies]
async-trait.workspace = true
azure_core = { workspace = true, features = ["reqwest"] }
futures.workspace = true
serde_json.workspace = true
serde.workspace = true
tracing.workspace = true
url.workspace = true
async-lock.workspace = true
pin-project.workspace = true

reqwest.workspace = true

[dev-dependencies]
uuid.workspace = true
azure_identity.workspace = true
azure_core_test = { workspace = true, features = ["tracing"] }
clap.workspace = true
reqwest = { workspace = true, features = ["http2"] }
time.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }

[lints]
workspace = true

[features]
default = ["hmac_rust"]
key_auth = [] # Enables support for key-based authentication (Primary Keys and Resource Tokens)
hmac_rust = ["azure_core/hmac_rust"]
hmac_openssl = ["azure_core/hmac_openssl"]
fault_injection = [] # Enables support for fault injection testing

[package.metadata.docs.rs]
features = [
  "key_auth",
  "hmac_rust",
  "hmac_openssl",
]
