[package]
name = "azure_data_cosmos"
version = "0.31.0"
description = "Rust wrappers around Microsoft Azure REST APIs - Azure Cosmos DB"
readme = "README.md"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage = "https://github.com/azure/azure-sdk-for-rust"
documentation = "https://docs.rs/azure_data_cosmos"
keywords = ["sdk", "cloud", "rest", "nosql"]
categories = ["api-bindings"]

[dependencies]
async-lock.workspace = true
async-trait.workspace = true
azure_core = { version = "0.32.0", default-features = false }
futures.workspace = true
pin-project.workspace = true
reqwest = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
azure_core_test = { workspace = true, features = ["tracing"] }
azure_identity = { version = "0.32.0" }
clap.workspace = true
reqwest = { workspace = true, features = ["http2"] }
time.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

[lints]
workspace = true

[features]
default = ["hmac_rust", "reqwest"]
reqwest = ["dep:reqwest", "azure_core/reqwest"]
key_auth = [
] # Enables support for key-based authentication (Primary Keys and Resource Tokens)
hmac_rust = ["azure_core/hmac_rust"]
hmac_openssl = ["azure_core/hmac_openssl"]
fault_injection = [] # Enables support for fault injection testing
allow_invalid_certificates = ["reqwest", "reqwest/native-tls"] # Enables accepting invalid TLS certificates (e.g., for emulator testing)

[package.metadata.docs.rs]
features = [
  "key_auth",
  "hmac_rust",
  "hmac_openssl",
  "allow_invalid_certificates",
]
