[package]
name = "typespec_macros"
version = "0.9.0"
authors.workspace = true
edition.workspace = true
description = "Procedural macros for client libraries built on typespec."
homepage = "https://typespec.io"
repository.workspace = true
license.workspace = true
categories = ["compilers", "development-tools"]
keywords = ["typespec"]

[lib]
proc-macro = true

[features]
debug = []

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
rustc_version.workspace = true
syn.workspace = true

[dev-dependencies]
cargo_metadata.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
typespec_client_core = { path = "../typespec_client_core", features = [
  "http",
  "json",
  "xml",
] }

[package.metadata.docs.rs]
features = []
