[package]
name = "azure_service_bus"
version = "0.1.0"
description = "Rust wrappers around Microsoft Azure REST APIs - Service Bus crate"
readme = "README.md"
authors = ["Microsoft Corp."]
license = "MIT"
repository = "https://github.com/azure/azure-sdk-for-rust"
homepage = "https://github.com/azure/azure-sdk-for-rust"
documentation = "https://docs.rs/azure_service_bus"

keywords = ["sdk", "azure", "rest", "iot", "cloud"]
categories = ["api-bindings"]

edition = "2018"

[dependencies]
azure_core = { path = "../core", version = "0.1.0" }
ring = "0.16"
base64 = "0.13"
chrono = "0.4"
hyper = "0.13"
log = "0.4"
url = "2.1"
hyper-rustls = "0.21"
http = "*"

[dev-dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["macros"] }
env_logger = "0.7"
reqwest = "*"
rand = "*"

[features]
test_e2e = []
