# Copyright (c) Microsoft Corp. All Rights Reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

[package]
name = "azure_messaging_eventhubs"
version = "0.12.0"
description = "Rust client for Azure Eventhubs Service"
readme = "README.md"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage = "https://github.com/azure/azure-sdk-for-rust"
documentation = "https://docs.rs/azure_messaging_eventhubs"
keywords = ["sdk", "cloud"]
categories = ["api-bindings"]

edition.workspace = true

[dependencies]
async-lock.workspace = true
async-stream.workspace = true
async-trait.workspace = true
azure_core = { path = "../../core/azure_core", version = "0.33.0", default-features = false }
azure_core_amqp.workspace = true
futures.workspace = true
rand.workspace = true
rand_chacha.workspace = true
tracing.workspace = true
url.workspace = true

[build-dependencies]
rustc_version.workspace = true

[dev-dependencies]
azure_core_amqp = { workspace = true, features = ["test"] }
azure_core_test = { workspace = true, features = ["tracing"] }
azure_identity.workspace = true
azure_messaging_eventhubs = { path = ".", features = [
  "in_memory_checkpoint_store",
] }
criterion.workspace = true
fe2o3-amqp = { workspace = true, features = ["tracing"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

[features]
in_memory_checkpoint_store = []
default = ["azure_core_amqp/default", "hmac_rust"]
hmac_rust = ["azure_core/hmac_rust"]
hmac_openssl = ["azure_core/hmac_openssl"]

[[bench]]
name = "benchmarks"
harness = false

[lints]
workspace = true
