[package]
name = "azure_storage_blob"
version = "0.10.0"
description = "Microsoft Azure Blob Storage client library for Rust"
readme = "README.md"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage = "https://github.com/azure/azure-sdk-for-rust"
documentation = "https://docs.rs/azure_storage_blob"
keywords = ["sdk", "cloud", "blobs"]
categories = ["api-bindings"]

[features]
default = ["azure_core/default"]

[dependencies]
async-trait.workspace = true
azure_core = { workspace = true, features = ["xml"] }
bytes.workspace = true
futures.workspace = true
pin-project.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
url.workspace = true
uuid.workspace = true

[lints]
workspace = true

[dev-dependencies]
azure_core_opentelemetry.workspace = true
azure_core_test = { workspace = true, features = [
  "tracing",
] }
azure_identity.workspace = true
azure_storage_blob_test.path = "../azure_storage_blob_test"
futures.workspace = true
opentelemetry-stdout.workspace = true
opentelemetry_sdk.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

[[bench]]
name = "perf"
path = "perf/perf_tests.rs"
harness = false
