[package]
name = "iothub"
version = "0.1.0"
authors = ["Microsoft Corp."]
edition = "2018"

[dependencies]
azure_core = { path = "../core", version = "0.1.0" }
base64 = "0.12"
bytes = "0.5"
chrono = "0.4"
crypto-mac = { version = "0.8.0", features = ["std"] }
hmac = "0.8"
hyper = "0.13"
hyper-tls = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
sha2 = "0.9"
url = "2.1"

[dev-dependencies]
tokio = { version = "0.2", features = ["macros"] }