[package]
name = "azure_core_test"
version = "0.1.0"
description = "Utilities for testing client libraries built on azure_core."
readme = "README.md"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage = "https://github.com/azure/azure-sdk-for-rust"
documentation = "https://docs.rs/azure_core"
keywords = ["sdk", "cloud", "rest", "iot", "testing"]
categories = ["development-tools::testing"]
edition.workspace = true
rust-version.workspace = true
publish = false

[features]
default = []
tracing = ["tracing-subscriber"]

[dependencies]
async-trait.workspace = true
azure_core = { workspace = true, features = ["test"] }
azure_core_test_macros.workspace = true
azure_identity.workspace = true
clap.workspace = true
dotenvy = "0.15.7"
futures.workspace = true
rand.workspace = true
rand_chacha.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = [
  "env-filter",
  "fmt",
], optional = true }
url.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
flate2.workspace = true
tar.workspace = true
tokio = { workspace = true, features = [
  "io-util",
  "process",
  "rt-multi-thread",
  "sync",
  "time",
] }
reqwest.workspace = true
zip.workspace = true

[dev-dependencies]
# Crate used in README.md example.
azure_security_keyvault_secrets = { path = "../../keyvault/azure_security_keyvault_secrets" }
clap.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
uuid.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { workspace = true, features = ["signal"] }

[lints]
workspace = true
