[properties]
boxed = [
    ["../../../azure-rest-api-specs/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/publicIpAddress.json", "PublicIPAddress" , "properties"],
    ["../../../azure-rest-api-specs/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/publicIpAddress.json", "PublicIPAddressPropertiesFormat", "ipConfiguration"],
    ["../../../azure-rest-api-specs/specification/network/resource-manager/Microsoft.Network/stable/2023-04-01/publicIpAddress.json", "PublicIPAddress" , "properties"],
    ["../../../azure-rest-api-specs/specification/network/resource-manager/Microsoft.Network/stable/2023-04-01/publicIpAddress.json", "PublicIPAddressPropertiesFormat", "ipConfiguration"],
    ["../../../azure-rest-api-specs/specification/network/resource-manager/Microsoft.Network/stable/2023-05-01/publicIpAddress.json", "PublicIPAddress" , "properties"],
    ["../../../azure-rest-api-specs/specification/network/resource-manager/Microsoft.Network/stable/2023-05-01/publicIpAddress.json", "PublicIPAddressPropertiesFormat", "ipConfiguration"],
]
