[package]
name = "azure-autorust"
version = "0.1.0"
authors = ["Cameron Taggart <cameron.taggart@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
autorust_codegen = { path = "../codegen" }
clap = { version = "4.0.2", features = ["derive"] }
