[package]
name = "azure_storage_queues"
version = "0.21.0"
description = "Azure Queue Storage crate from the Azure SDK for Rust"
readme = "README.md"
authors = ["Microsoft Corp."]
license = "MIT"
repository = "https://github.com/azure/azure-sdk-for-rust"
homepage = "https://github.com/azure/azure-sdk-for-rust/tree/legacy"
documentation = "https://docs.rs/azure_storage_queues"
keywords = ["sdk", "azure", "storage", "queues"]
categories = ["api-bindings"]
edition = "2021"

[dependencies]
azure_core = { path = "../core", version = "0.21", default-features=false, features = ["xml"] }
azure_storage = { path = "../storage", version = "0.21", default-features=false }
time = "0.3.10"
futures = "0.3"
tracing = "0.1.40"
serde = { version = "1.0", features=["derive"] }
uuid = { version = "1.0", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.0", features = ["v4"] }
tracing-subscriber = "0.3"

[features]
default = ["enable_reqwest", "hmac_rust"]
test_e2e = []
enable_reqwest = ["azure_core/enable_reqwest", "azure_storage/enable_reqwest"]
enable_reqwest_rustls = ["azure_core/enable_reqwest_rustls", "azure_storage/enable_reqwest_rustls"]
test_integration = []
hmac_openssl = ["azure_core/hmac_openssl"]
hmac_rust = ["azure_core/hmac_rust"]

[package.metadata.docs.rs]
features = ["enable_reqwest", "enable_reqwest_rustls", "hmac_rust", "hmac_openssl"]
