[package]
name = "azure_storage_queues"
version = "0.5.0"
description = "Azure Queue Storage crate from the Azure SDK for Rust"
readme = "README.md"
authors = ["Microsoft Corp."]
license = "MIT"
repository = "https://github.com/azure/azure-sdk-for-rust"
homepage = "https://github.com/azure/azure-sdk-for-rust"
documentation = "https://docs.rs/azure_storage_queues"
keywords = ["sdk", "azure", "storage", "queues"]
categories = ["api-bindings"]
edition = "2021"

[dependencies]
azure_core = { path = "../core", version = "0.4", default-features=false }
azure_storage = { path = "../storage", version = "0.5", default-features=false }
time = "0.3.10"
futures = "0.3"
log = "0.4"
serde = { version = "1.0" }
serde_derive = "1.0"
serde_json = "1.0"
serde-xml-rs = "0.5"
uuid = { version = "1.0", features = ["v4"] }
url = "2.2"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.0", features = ["v4"] }

[features]
default = ["enable_reqwest"]
test_e2e = []
enable_reqwest = ["azure_core/enable_reqwest", "azure_storage/enable_reqwest"]
enable_reqwest_rustls = ["azure_core/enable_reqwest_rustls", "azure_storage/enable_reqwest_rustls"]
