# Copyright (c) Microsoft Corp. All Rights Reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

[package]
name = "azure_messaging_servicebus"
version = "0.22.0"
description = "Rust client for Azure Service Bus"
readme = "README.md"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage = "https://github.com/azure/azure-sdk-for-rust"
documentation = "https://docs.rs/azure_messaging_servicebus"
keywords = ["sdk", "azure", "messaging", "cloud", "servicebus"]
categories = ["api-bindings"]
edition.workspace = true
publish = false

[dependencies]
async-lock.workspace = true
async-stream.workspace = true
async-trait.workspace = true
azure_core = { path = "../../core/azure_core", version = "0.33.0", default-features = false }
azure_core_amqp.workspace = true
futures.workspace = true
rand.workspace = true
rand_chacha.workspace = true
serde = { workspace = true, features = ["derive"] }
time.workspace = true
tracing.workspace = true

[features]
default = ["azure_core_amqp/default"]

[dev-dependencies]
azure_core_amqp = { workspace = true, features = ["test"] }
azure_core_test = { workspace = true, features = ["tracing"] }
azure_identity.workspace = true
azure_messaging_servicebus = { path = "." }
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

[lints]
workspace = true
