[package]
name = "azure_security_keyvault_certificates"
version = "0.11.0"
description = "Rust wrappers around Microsoft Azure REST APIs - Azure Key Vault Certificates"
readme = "README.md"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage = "https://github.com/azure/azure-sdk-for-rust"
documentation = "https://docs.rs/azure_security_keyvault_certificates"
keywords = ["sdk", "cloud"]
categories = ["api-bindings"]

[features]
default = ["azure_core/default"]

[dependencies]
async-lock = { workspace = true }
async-trait = { workspace = true }
azure_core = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
azure_core_test = { workspace = true, features = [
  "tracing",
] }
azure_identity.workspace = true
azure_security_keyvault_keys = { path = "../azure_security_keyvault_keys" }
azure_security_keyvault_test = { path = "../azure_security_keyvault_test" }
include-file.workspace = true
openssl.workspace = true
rand.workspace = true
tokio.workspace = true
tracing.workspace = true

[build-dependencies]
rustc_version.workspace = true

[lints]
workspace = true
