[workspace]
# This package is INTENTIONALLY omitted from the workspace because it contains files that do not compile (as part of testing compilation error reporting)
# So we create a workspace node to tell cargo this is the root of a workspace

[package]
name = "compilation-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
typespec_client_core = { path = "../../typespec_client_core", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
