[package]
name = "typespec_client_core"
version = "0.9.0"
authors.workspace = true
edition.workspace = true
description = "Client runtime for TypeSpec-generated libraries."
homepage = "https://typespec.io"
repository.workspace = true
license.workspace = true
categories = ["compilers", "development-tools"]
keywords = ["typespec"]

[dependencies]
async-trait.workspace = true
base64.workspace = true
dyn-clone.workspace = true
futures.workspace = true
gloo-timers = { workspace = true, optional = true }
pin-project.workspace = true
rand.workspace = true
reqwest = { workspace = true, optional = true }
rust_decimal = { workspace = true, optional = true }
serde.workspace = true
serde_json = { workspace = true, optional = true }
time.workspace = true
tokio = { workspace = true, optional = true }
tracing.workspace = true
typespec = { workspace = true, default-features = false }
typespec_macros = { workspace = true, optional = true }
url.workspace = true
uuid.workspace = true
wasm-bindgen-futures = { workspace = true, optional = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "time"] }

[dev-dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
typespec_macros.path = "../typespec_macros"

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
tokio = { workspace = true, features = ["fs"] }

[target.'cfg(target_family = "wasm")'.dev-dependencies]
tokio.workspace = true
getrandom = { workspace = true, features = ["wasm_js"] }
uuid = { workspace = true, features = ["v4", "js"] }
wasm-bindgen-test.workspace = true

[features]
default = [
  "http",
  "json",
  "reqwest",
  "reqwest_deflate",
  "reqwest_gzip",
  "reqwest_native_tls",
]
debug = ["typespec_macros?/debug"]
decimal = ["dep:rust_decimal"]
derive = ["dep:typespec_macros"]
http = ["typespec/http"]
json = ["dep:serde_json", "typespec/json"]
reqwest = ["dep:reqwest"]
reqwest_deflate = ["reqwest", "reqwest/deflate"]
reqwest_gzip = ["reqwest", "reqwest/gzip"]
reqwest_native_tls = ["reqwest", "reqwest/native-tls"]
test = [] # Enables extra tracing including error bodies that may contain PII.
tokio = ["tokio/sync", "tokio/time"]
wasm_bindgen = ["dep:wasm-bindgen-futures", "gloo-timers/futures"]
xml = ["dep:serde_json", "typespec/xml"] # Uses serde_json::Value for `unknown` TypeSpec scalar.

[[example]]
name = "core_binary_data_request"
required-features = ["tokio"]

[[example]]
name = "core_stream_response"
required-features = ["derive"]

[package.metadata.docs.rs]
features = [
  "debug",
  "decimal",
  "derive",
  "http",
  "json",
  "reqwest",
  "reqwest_deflate",
  "reqwest_gzip",
  "reqwest_native_tls",
  "tokio",
  "wasm_bindgen",
  "xml",
]

[lints]
workspace = true
