[package]
name = "typespec_client_core"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "Client runtime for TypeSpec-generated libraries."
homepage = "https://typespec.io"
repository.workspace = true
license.workspace = true
categories = ["compilers", "development-tools"]
keywords = ["typespec"]

[dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
dyn-clone = { workspace = true }
futures = { workspace = true }
http-types = { workspace = true, optional = true }
pin-project = { workspace = true }
quick-xml = { workspace = true, optional = true }
rand = { workspace = true }
reqwest = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true }
typespec = { workspace = true, default-features = false }
url = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "time"] }

[dev-dependencies]
once_cell = { workspace = true }
tokio.workspace = true

[features]
default = [
    "http",
    "json",
    "reqwest",
    "reqwest_gzip",
    "reqwest_rustls",
    "tokio_sleep",
]
http = ["dep:http-types", "typespec/http"]
json = ["typespec/json"]
reqwest = ["dep:reqwest", "reqwest/default-tls"]
reqwest_gzip = ["reqwest/gzip"]
reqwest_rustls = ["reqwest/rustls-tls"]
tokio_sleep = ["tokio/time"]
xml = ["dep:quick-xml"]

[package.metadata.docs.rs]
all-features = true
