[package]
name = "azure_security_keyvault_test"
version = "0.1.0"
description = "Common utilities for Key Vault tests"
readme = "README.md"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage = "https://github.com/azure/azure-sdk-for-rust"
keywords = ["sdk", "cloud", "rest", "vault", "testing"]
categories = ["development-tools"]
publish = false

[dependencies]
tokio = { workspace = true, features = ["rt"] }

[lints]
workspace = true
