[package]
name = "azure_data_cosmos_native"
publish = false
description = "The Cosmos Native Client is a C library, written in Rust but exporting a C-compatible API, that provides a full SDK for Azure Cosmos DB."
version = "0.27.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "azurecosmos"
crate-type = ["cdylib", "staticlib"]

[dependencies]
futures.workspace = true
tokio = { workspace = true, optional = true, features = ["rt-multi-thread", "macros"] }
serde_json = { workspace = true, features = ["raw_value"] }
azure_core.workspace = true
azure_data_cosmos = { path = "../azure_data_cosmos", features = [ "key_auth", "preview_query_engine" ] }
tracing.workspace = true
tracing-subscriber = { workspace = true, optional = true, features = ["fmt", "env-filter"] }

[features]
default = ["tokio", "reqwest", "tracing"]
tokio = ["dep:tokio"]
reqwest = ["azure_core/reqwest"]
tracing = ["dep:tracing-subscriber"]

[build-dependencies]
cbindgen = "0.29.0"

[lints]
workspace = true
