[package]
name = "azure_core_macros"
version = "0.3.1"
description = "Procedural macros for client libraries built on azure_core."
readme = "README.md"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage = "https://github.com/azure/azure-sdk-for-rust"
documentation = "https://docs.rs/azure_core"
keywords = ["azure", "cloud", "iot", "rest", "sdk"]
categories = ["development-tools"]
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
tracing.workspace = true
typespec_client_core = { workspace = true, features = ["http", "json"] }

[dev-dependencies]
tokio.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
