[package]
name = "azure_core_opentelemetry"
version = "0.7.0"
description = "OpenTelemetry integration for the Azure SDK for Rust"
readme = "README.md"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage = "https://github.com/azure/azure-sdk-for-rust"
documentation = "https://docs.rs/azure_core_tracing_opentelemetry"
keywords = ["sdk", "cloud", "tracing", "observability"]
categories = ["api-bindings", "development-tools::debugging"]
edition.workspace = true
rust-version.workspace = true

[features]
default = ["azure_core/default"]

[dependencies]
azure_core.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
tracing.workspace = true

[dev-dependencies]
azure_core_test = { workspace = true, features = ["tracing"] }
azure_core_test_macros.workspace = true
azure_identity.workspace = true
opentelemetry_sdk = { workspace = true, features = ["testing"] }
tokio.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
