[package]
name = "check_api_superset"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[build-dependencies]
serde = { workspace = true }
toml = { workspace = true }

[dependencies]
rustdoc-types = { workspace = true }
serde_json = { workspace = true }
