name: Check All Features for Services

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  RUSTFLAGS: --deny warnings --allow unused_attributes --allow unreachable-code --allow unused-assignments
  CARGO_INCREMENTAL: 0

jobs:
  test-services:
    name: Services Tests
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - uses: Swatinem/rust-cache@v1

    - name: check all features
      run: cargo check --manifest-path services/Cargo.toml --all-features

    - name: display free disk space
      run: df -h /
      if: ${{ always() }}
